<?php
// ESTO ES SIMPLEMENTE PARA EL BOTÓN DE CERRAR SESIÓN


// SIEMPRE QUE ESTEMOS TRABAJANDO LA SESIÓN
// DEBEMOS INICIAR LA SESIÓN PARA DESPUÉS CERRARLA
session_start();
session_destroy();
// PARA QUE AL CERRAR LA SESIÓN LLEVE AL INDEX
// header("location: ../../index.html");

// PARA QUE AL CERRAR LA SESIÓN LLEVE NUEVAMENTE AL LOGIN & REGISTER
header("location: ../index.php");

//     <!-- FINALIZACIÓN DEL CÓDIGO PHP
// POR: FRANCISCO QUIÑONES MALDONADO -->